//
// ArticleList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ArticleList: Codable, JSONEncodable, Hashable {

    public var response: ArticleListResponse

    public init(response: ArticleListResponse) {
        self.response = response
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case response
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(response, forKey: .response)
    }
}

